import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

// Run through the ESLint CLI rather than `next lint`, which is deprecated and
// removed in Next 16. The CLI does not apply Next's implicit ignores, so the
// build output and generated files are listed explicitly below.
const eslintConfig = [
  {
    ignores: [
      ".next/**",
      "out/**",
      "build/**",
      "node_modules/**",
      "next-env.d.ts",
      // Generated by `drizzle-kit pull`; reformatting it would make the next
      // regeneration a large diff.
      "src/db/introspected/**",
    ],
  },
  ...compat.extends("next/core-web-vitals"),
];

export default eslintConfig;
