import os, re, json, openpyxl
budget=json.load(open(os.environ.get("ORG_PERSONNEL_BUDGET_JSON", "/tmp/org_personnel_budget.json")))
# The Compensation Plan workbook is a manual download, so its location differs per
# machine and per budget year; naming it here would only ever be right on one laptop.
XLSX=os.environ.get("COMP_PLAN_XLSX")
if not XLSX:
    raise SystemExit(
        "COMP_PLAN_XLSX is not set. Point it at the downloaded FY City of Portland "
        "Compensation Plan workbook, e.g.\n"
        "  COMP_PLAN_XLSX=~/Downloads/FY-25-26-City-of-Portland-Comp-Plan_0.xlsx "
        "python3 ingest/build-org-personnel.py"
    )
XLSX=os.path.expanduser(XLSX)
wb=openpyxl.load_workbook(XLSX, read_only=True, data_only=True); ws=wb.active
rows=list(ws.iter_rows(values_only=True)); hdr=None
for i,r in enumerate(rows):
    cells=[str(c).strip() if c is not None else "" for c in r]
    if "Job ID" in cells and "Classification" in cells and "Rate Type" in cells:
        hdr=i; cols={n:j for j,n in enumerate(cells)}; break
JOB=cols["Job ID"]; BARG=cols["Barg Unit"]; CLS=cols["Classification"]; RT=cols["Rate Type"]; start=cols["Minimum"]
comp={}
for r in rows[hdr+1:]:
    if r is None or r[JOB] is None: continue
    job=str(int(r[JOB])) if isinstance(r[JOB],(int,float)) else str(r[JOB]).strip()
    if str(r[RT]).strip()!="Annual": continue
    vals=[float(c) for c in r[start:] if isinstance(c,(int,float)) and c and c>1000]
    if vals: comp[job]={"barg":str(r[BARG]).strip() if r[BARG] else "","min":int(min(vals)),"max":int(max(vals))}
out={}
for nid, recs in budget.items():
    classes=[]
    for cid,r in recs.items():
        if r["fte"]<=0: continue
        c=comp.get(cid)
        smin,smax,barg=(c["min"],c["max"],c["barg"]) if c else (r.get("bMin"),r.get("bMax"),None)
        if smin==0 and (smax==0 or smax is None): smin=smax=None
        classes.append({"title":re.sub(r'\s+',' ',r["title"]).strip(),"fte":round(r["fte"],2),
            "cost":int(r["amount"]),"salMin":smin,"salMax":smax,"barg":barg or None})
    classes.sort(key=lambda x:-x["cost"])
    out[nid]={"classifications":classes,"totalFte":round(sum(c["fte"] for c in classes),2),
              "totalCost":sum(c["cost"] for c in classes),"classCount":len(classes)}
def esc(s): return s.replace("\\","\\\\").replace('"','\\"')
L=['// Per-bureau personnel detail — deepest authoritative public layer.',
'// Source: FY2025-26 Adopted Budget Vol 1 FTE Summary (authorized FTE + budgeted $ by',
'// job classification) joined by Class ID to the FY2025-26 Compensation Plan (salary',
'// band + bargaining unit). Generated by ingest/parse-org-personnel.py + build-org-personnel.py.','',
'export const PERSONNEL_FY = "FY2025-26 Adopted";',
'export const PERSONNEL_SOURCE =','  "https://www.portland.gov/budget/documents/fy-2025-26-city-portland-adopted-budget-vol-1-city-summaries-and-bureau-budgets/download";','',
'export interface PersonnelClass {','  title: string;','  fte: number;','  cost: number;',
'  salaryMin: number | null;','  salaryMax: number | null;','  bargUnit: string | null;','}',
'export interface BureauPersonnel {','  classifications: PersonnelClass[];','  totalFte: number;',
'  totalCost: number;','  classCount: number;','}','',
'export const BUREAU_PERSONNEL: Record<string, BureauPersonnel> = {']
for nid,b in sorted(out.items()):
    L.append(f'  "{nid}": {{ totalFte: {b["totalFte"]}, totalCost: {b["totalCost"]}, classCount: {b["classCount"]}, classifications: [')
    for c in b["classifications"]:
        smin="null" if c["salMin"] is None else str(c["salMin"]); smax="null" if c["salMax"] is None else str(c["salMax"])
        barg="null" if not c["barg"] else f'"{esc(c["barg"])}"'
        L.append(f'    {{ title: "{esc(c["title"])}", fte: {c["fte"]}, cost: {c["cost"]}, salaryMin: {smin}, salaryMax: {smax}, bargUnit: {barg} }},')
    L.append("  ] },")
L.append("};")
open("src/data/org-personnel.ts","w").write("\n".join(L)+"\n")
print("regenerated org-personnel.ts with cost; total citywide personnel $ =",
      "${:,}".format(sum(b["totalCost"] for b in out.values())))
print("PPB totalCost ${:,} | PPB totalFte {}".format(out["ppb"]["totalCost"], out["ppb"]["totalFte"]))
