import os, json

# The per-bureau "Bureau Programs" extraction is produced out-of-band and lands in a
# scratch path that is unique to each run, so the caller has to say where it is.
WORKFLOW_JSON=os.environ.get("ORG_FINANCE_WORKFLOW_JSON")
if not WORKFLOW_JSON:
    raise SystemExit(
        "ORG_FINANCE_WORKFLOW_JSON is not set. Point it at the bureau-programs "
        "extraction output, e.g.\n"
        "  ORG_FINANCE_WORKFLOW_JSON=/path/to/extraction.json "
        "python3 ingest/build-org-finance.py"
    )
wf=json.load(open(os.path.expanduser(WORKFLOW_JSON)))
results={r["id"]:r for r in wf["result"]["results"]}
OPTOT={"city-attorney":22300219,"city-auditor":14185501,"cbo":4437127,"office-city-administrator":95342565,
"childrens-levy":29157997,"city-council":19548454,"office-city-operations":49715513,"fpdr":310269063,
"ppd":97732402,"office-ced":71819077,"boec":39394224,"pbem":9394805,"bes":1431010465,"pfr":206281687,
"bff":288899941,"office-government-relations":3029890,"phb":244215819,"bhr":218896003,"cfo-office":274977555,
"mayor":3496592,"civic-life":5068855,"office-equity":3242998,"ocpa":2104114,"parks":541392393,
"ppb":316692335,"bps":843956566,"community-safety":30899669,"pbot":610757226,"bts":146406086,
"water":2183344599,"office-public-works":2603945}
fin={}
for nid,optot in OPTOT.items():
    deps=results.get(nid,{}).get("departments",[]) or []
    # recompute pct against the bureau operating total (consistent denominator), cap top 10
    deps=[{"name":d["name"],"budget":int(d["budget"]),"pct":round(d["budget"]/optot*100,1)} for d in deps if d.get("budget")]
    deps.sort(key=lambda d:-d["budget"]); deps=deps[:10]
    fin[nid]={"operatingTotal":optot,"departments":deps,"shownPct":round(sum(d["pct"] for d in deps),1)}
def esc(s): return s.replace("\\","\\\\").replace('"','\\"')
L=['// Per-bureau finance: operating (all-funds) total + program/department budget breakdown.',
'// Operating totals from the budget per-bureau "Bureau Overview"; departments extracted',
'// from the budget "Bureau Programs" charts (workflow), with pct RECOMPUTED as a share of',
'// the operating total for a consistent denominator. NOTE: this is TOTAL program budget',
'// (all funds: capital, debt, grants, pass-throughs like PCEF) — a different, much larger',
'// denominator than the personnel/salary cost in org-personnel.ts. `shownPct` is the share',
'// of the bureau covered by the listed (top) programs; the remainder is smaller programs.',
'// Generated by ingest/build-org-finance.py.','',
'export const FINANCE_FY = "FY2025-26 Adopted";',
'export const FINANCE_SOURCE =','  "https://www.portland.gov/budget/documents/fy-2025-26-city-portland-adopted-budget-vol-1-city-summaries-and-bureau-budgets/download";','',
'export interface Department { name: string; budget: number; pct: number; }',
'export interface BureauFinance { operatingTotal: number; shownPct: number; departments: Department[]; }','',
'export const BUREAU_FINANCE: Record<string, BureauFinance> = {']
for nid in sorted(fin):
    f=fin[nid]
    L.append(f'  "{nid}": {{ operatingTotal: {f["operatingTotal"]}, shownPct: {f["shownPct"]}, departments: [')
    for d in f["departments"]:
        L.append(f'    {{ name: "{esc(d["name"])}", budget: {d["budget"]}, pct: {d["pct"]} }},')
    L.append("  ] },")
L.append("};")
open("src/data/org-analysis.ts","w").write("\n".join(L)+"\n")
cp=sum(1 for f in fin.values() if f["departments"])
print(f"wrote org-analysis.ts: {len(fin)} bureaus, {cp} with department breakdowns")
print("PPB depts:", [(d['name'],d['pct']) for d in fin['ppb']['departments'][:4]])
print("Water depts:", [(d['name'],d['pct']) for d in fin['water']['departments'][:4]])
