/**
 * Seed real_estate.listings with sample data based on real Portland addresses.
 *
 * Usage:  npx tsx scripts/seed-real-estate.ts
 */

import postgres from "postgres";

const sql = postgres(
  process.env.DATABASE_URL ||
    "postgresql://edankrolewicz@localhost:5432/portland_dashboard",
);

async function main() {
  console.log("Creating real_estate schema and listings table...");

  await sql`CREATE SCHEMA IF NOT EXISTS real_estate`;

  await sql`
    CREATE TABLE IF NOT EXISTS real_estate.listings (
      id              SERIAL PRIMARY KEY,
      title           TEXT NOT NULL,
      address         TEXT NOT NULL,
      neighborhood    TEXT NOT NULL,
      sqft            INTEGER NOT NULL,
      space_type      TEXT NOT NULL,
      asking_rent     NUMERIC(10,2),
      pcb_terms       JSONB DEFAULT '{}',
      condition       TEXT DEFAULT 'move-in ready',
      vacancy_duration TEXT,
      listed_date     DATE DEFAULT CURRENT_DATE,
      status          TEXT DEFAULT 'available',
      description     TEXT,
      amenities       TEXT[] DEFAULT '{}',
      floor           TEXT,
      contact_email   TEXT,
      lat             DOUBLE PRECISION,
      lon             DOUBLE PRECISION,
      images          TEXT[] DEFAULT '{}',
      created_at      TIMESTAMP DEFAULT NOW()
    )
  `;

  // Clear existing seed data
  await sql`DELETE FROM real_estate.listings`;

  console.log("Inserting sample listings...");

  const listings = [
    {
      title: "Ground-Floor Retail on SW Morrison",
      address: "811 SW Morrison St, Portland, OR 97205",
      neighborhood: "Downtown",
      sqft: 1800,
      space_type: "retail",
      asking_rent: 22.5,
      pcb_terms: { popup_available: true, graduated_rent: true, graduated_schedule: "Year 1: 50%, Year 2: 75%, Year 3: 100%" },
      condition: "white box",
      vacancy_duration: "8 months",
      description: "Corner retail space with floor-to-ceiling windows on SW Morrison. High foot traffic location near Pioneer Courthouse Square. Previous tenant was a boutique clothing store. Ideal for food & beverage, retail, or creative studio.",
      amenities: ["ADA accessible", "Street parking", "Transit adjacent", "Loading zone"],
      floor: "Ground",
      contact_email: "leasing@portlandcommons.org",
      lat: 45.5189,
      lon: -122.6795,
    },
    {
      title: "Creative Office Loft in the Pearl",
      address: "1022 NW Marshall St, Portland, OR 97209",
      neighborhood: "Pearl District",
      sqft: 3200,
      space_type: "office",
      asking_rent: 28.0,
      pcb_terms: { popup_available: false, graduated_rent: true, graduated_schedule: "Year 1: 60%, Year 2: 80%, Year 3: 100%" },
      condition: "move-in ready",
      vacancy_duration: "3 months",
      description: "Open-plan creative office with exposed brick, timber beams, and polished concrete floors. 14-foot ceilings with skylights. Located in the heart of the Pearl District, steps from Jamison Square and the streetcar.",
      amenities: ["Exposed brick", "Skylights", "Freight elevator", "Bike storage", "Streetcar adjacent"],
      floor: "3rd",
      contact_email: "leasing@portlandcommons.org",
      lat: 45.5310,
      lon: -122.6834,
    },
    {
      title: "Restaurant Space with Hood System",
      address: "3556 SE Hawthorne Blvd, Portland, OR 97214",
      neighborhood: "Hawthorne",
      sqft: 2400,
      space_type: "restaurant",
      asking_rent: 32.0,
      pcb_terms: { popup_available: true, graduated_rent: true, graduated_schedule: "Year 1: 40%, Year 2: 65%, Year 3: 85%, Year 4: 100%" },
      condition: "previous restaurant",
      vacancy_duration: "5 months",
      description: "Turn-key restaurant space on Hawthorne. Full commercial kitchen with Type I hood system, walk-in cooler, and grease trap. Outdoor patio seating for 24. Previous tenant operated a Thai restaurant for 12 years.",
      amenities: ["Hood system", "Walk-in cooler", "Patio seating", "Liquor license transferable", "Street parking"],
      floor: "Ground",
      contact_email: "leasing@portlandcommons.org",
      lat: 45.5121,
      lon: -122.6285,
    },
    {
      title: "Maker Space in Central Eastside",
      address: "234 SE 3rd Ave, Portland, OR 97214",
      neighborhood: "Central Eastside",
      sqft: 5500,
      space_type: "industrial",
      asking_rent: 14.0,
      pcb_terms: { popup_available: false, graduated_rent: true, graduated_schedule: "Year 1: 55%, Year 2: 75%, Year 3: 100%" },
      condition: "industrial shell",
      vacancy_duration: "12 months",
      description: "Raw industrial space perfect for makers, artisans, or light manufacturing. Drive-in bay door, 3-phase power, 20-foot clear height. Located in the CEID with easy access to I-5 and the Morrison Bridge.",
      amenities: ["Drive-in bay", "3-phase power", "20ft ceiling", "Loading dock", "Freight access"],
      floor: "Ground",
      contact_email: "leasing@portlandcommons.org",
      lat: 45.5165,
      lon: -122.6615,
    },
    {
      title: "Pop-Up Ready on NW 23rd",
      address: "718 NW 23rd Ave, Portland, OR 97210",
      neighborhood: "Nob Hill",
      sqft: 950,
      space_type: "retail",
      asking_rent: 18.0,
      pcb_terms: { popup_available: true, popup_minimum: "1 month", popup_rate: 1200, graduated_rent: false },
      condition: "move-in ready",
      vacancy_duration: "2 months",
      description: "Intimate retail space on Portland's premier shopping street. Freshly painted with new flooring. Perfect for pop-up retail, gallery shows, or a small boutique. Short-term leases welcome through PCB program.",
      amenities: ["Street frontage", "Display windows", "ADA accessible", "Metered parking"],
      floor: "Ground",
      contact_email: "leasing@portlandcommons.org",
      lat: 45.5316,
      lon: -122.6988,
    },
    {
      title: "Mixed-Use Suite on Alberta",
      address: "2805 NE Alberta St, Portland, OR 97211",
      neighborhood: "Alberta Arts District",
      sqft: 1400,
      space_type: "flex",
      asking_rent: 20.0,
      pcb_terms: { popup_available: true, graduated_rent: true, graduated_schedule: "Year 1: 50%, Year 2: 75%, Year 3: 100%" },
      condition: "move-in ready",
      vacancy_duration: "4 months",
      description: "Flexible ground-floor suite in the heart of the Alberta Arts District. Zoned for retail, office, or studio use. Large front windows and 12-foot ceilings. Join a vibrant corridor of independent businesses and galleries.",
      amenities: ["Flexible zoning", "12ft ceilings", "Display windows", "Street parking", "Bike lane"],
      floor: "Ground",
      contact_email: "leasing@portlandcommons.org",
      lat: 45.5590,
      lon: -122.6370,
    },
    {
      title: "Professional Office in Lloyd District",
      address: "1515 NE Broadway, Portland, OR 97232",
      neighborhood: "Lloyd District",
      sqft: 2100,
      space_type: "office",
      asking_rent: 19.5,
      pcb_terms: { popup_available: false, graduated_rent: true, graduated_schedule: "Year 1: 65%, Year 2: 85%, Year 3: 100%" },
      condition: "move-in ready",
      vacancy_duration: "6 months",
      description: "Modern professional office suite near the Lloyd Center MAX station. Open floor plan with private conference room and kitchenette. Ideal for professional services, tech startup, or nonprofit headquarters.",
      amenities: ["MAX station adjacent", "Conference room", "Kitchenette", "On-site parking", "Security"],
      floor: "2nd",
      contact_email: "leasing@portlandcommons.org",
      lat: 45.5342,
      lon: -122.6456,
    },
    {
      title: "Cafe & Bakery Shell on Division",
      address: "3016 SE Division St, Portland, OR 97202",
      neighborhood: "Division",
      sqft: 1600,
      space_type: "restaurant",
      asking_rent: 26.0,
      pcb_terms: { popup_available: true, graduated_rent: true, graduated_schedule: "Year 1: 45%, Year 2: 70%, Year 3: 90%, Year 4: 100%" },
      condition: "white box",
      vacancy_duration: "7 months",
      description: "White-box space on the booming Division corridor. Plumbing roughed in for commercial kitchen. Prominent corner location with good signage visibility. Strong residential density and foot traffic.",
      amenities: ["Corner location", "Plumbing roughed in", "Signage opportunity", "Bike parking", "Bus stop adjacent"],
      floor: "Ground",
      contact_email: "leasing@portlandcommons.org",
      lat: 45.5054,
      lon: -122.6354,
    },
    {
      title: "Warehouse Conversion on Sandy",
      address: "4215 NE Sandy Blvd, Portland, OR 97213",
      neighborhood: "Hollywood",
      sqft: 4800,
      space_type: "flex",
      asking_rent: 16.5,
      pcb_terms: { popup_available: false, graduated_rent: true, graduated_schedule: "Year 1: 50%, Year 2: 70%, Year 3: 90%, Year 4: 100%" },
      condition: "partially renovated",
      vacancy_duration: "14 months",
      description: "Partially converted warehouse with soaring ceilings and original timber frame. Suitable for creative office, event space, brewery/taproom, or retail showroom. The Hollywood district is experiencing significant reinvestment.",
      amenities: ["Timber frame", "18ft ceilings", "Off-street parking", "Loading access", "Near Hollywood TC"],
      floor: "Ground",
      contact_email: "leasing@portlandcommons.org",
      lat: 45.5382,
      lon: -122.6181,
    },
    {
      title: "Micro-Retail on Mississippi",
      address: "3971 N Mississippi Ave, Portland, OR 97227",
      neighborhood: "Mississippi",
      sqft: 650,
      space_type: "retail",
      asking_rent: 24.0,
      pcb_terms: { popup_available: true, popup_minimum: "2 weeks", popup_rate: 800, graduated_rent: false },
      condition: "move-in ready",
      vacancy_duration: "1 month",
      description: "Charming micro-retail space on Mississippi Ave. Perfect for a small boutique, jewelry studio, or specialty food shop. Excellent foot traffic and neighboring businesses include Meadow, Paxton Gate, and numerous eateries.",
      amenities: ["High foot traffic", "Neighboring anchors", "Street parking", "Bike corrals"],
      floor: "Ground",
      contact_email: "leasing@portlandcommons.org",
      lat: 45.5530,
      lon: -122.6758,
    },
    {
      title: "Corner Suite at Union Station",
      address: "800 NW 6th Ave, Portland, OR 97209",
      neighborhood: "Old Town / Chinatown",
      sqft: 2800,
      space_type: "office",
      asking_rent: 15.0,
      pcb_terms: { popup_available: false, graduated_rent: true, graduated_schedule: "Year 1: 40%, Year 2: 60%, Year 3: 80%, Year 4: 100%" },
      condition: "needs renovation",
      vacancy_duration: "24 months",
      description: "Large corner office suite near Union Station. The Old Town / Chinatown neighborhood is a priority revitalization area with significant PCB incentives. Aggressive graduated rent schedule reflects the area's redevelopment potential.",
      amenities: ["Union Station adjacent", "Bus mall access", "Historic character", "Large windows"],
      floor: "2nd",
      contact_email: "leasing@portlandcommons.org",
      lat: 45.5288,
      lon: -122.6764,
    },
    {
      title: "Gallery & Studio on First Thursday",
      address: "916 NW Flanders St, Portland, OR 97209",
      neighborhood: "Pearl District",
      sqft: 2000,
      space_type: "flex",
      asking_rent: 30.0,
      pcb_terms: { popup_available: true, popup_minimum: "1 month", popup_rate: 2500, graduated_rent: true, graduated_schedule: "Year 1: 60%, Year 2: 80%, Year 3: 100%" },
      condition: "gallery ready",
      vacancy_duration: "2 months",
      description: "Pristine gallery-grade space on the First Thursday art walk circuit. White walls, track lighting, polished concrete, and controlled HVAC. Ideal for art gallery, design showroom, or creative retail concept.",
      amenities: ["Gallery lighting", "Climate controlled", "Loading access", "Security system", "Street frontage"],
      floor: "Ground",
      contact_email: "leasing@portlandcommons.org",
      lat: 45.5270,
      lon: -122.6810,
    },
    {
      title: "Food Hall Stall at Pine Street Market",
      address: "126 SW 2nd Ave, Portland, OR 97204",
      neighborhood: "Downtown",
      sqft: 400,
      space_type: "restaurant",
      asking_rent: 55.0,
      pcb_terms: { popup_available: true, popup_minimum: "3 months", popup_rate: 1800, graduated_rent: true, graduated_schedule: "Year 1: 50%, Year 2: 80%, Year 3: 100%" },
      condition: "built-out stall",
      vacancy_duration: "1 month",
      description: "Turnkey food stall in a high-traffic food hall concept downtown. Shared seating, dishwashing, and refuse. Includes basic kitchen buildout. Perfect for a PCB-certified food entrepreneur testing a concept.",
      amenities: ["Shared seating", "Dishwashing", "Refuse handling", "High foot traffic", "Central location"],
      floor: "Ground",
      contact_email: "leasing@portlandcommons.org",
      lat: 45.5189,
      lon: -122.6735,
    },
    {
      title: "Co-Working Anchor in Sellwood",
      address: "7979 SE 13th Ave, Portland, OR 97202",
      neighborhood: "Sellwood-Moreland",
      sqft: 3800,
      space_type: "office",
      asking_rent: 18.0,
      pcb_terms: { popup_available: false, graduated_rent: true, graduated_schedule: "Year 1: 55%, Year 2: 75%, Year 3: 100%" },
      condition: "move-in ready",
      vacancy_duration: "5 months",
      description: "Spacious office suitable for co-working operator or large team. Ground floor with abundant natural light. The Sellwood neighborhood has strong residential support and an engaged business association.",
      amenities: ["Natural light", "ADA accessible", "On-site parking", "Kitchen area", "Fiber internet"],
      floor: "Ground",
      contact_email: "leasing@portlandcommons.org",
      lat: 45.4672,
      lon: -122.6536,
    },
    {
      title: "Brewery-Ready Space on Foster",
      address: "5214 SE Foster Rd, Portland, OR 97206",
      neighborhood: "Foster-Powell",
      sqft: 4200,
      space_type: "industrial",
      asking_rent: 12.0,
      pcb_terms: { popup_available: false, graduated_rent: true, graduated_schedule: "Year 1: 45%, Year 2: 65%, Year 3: 85%, Year 4: 100%" },
      condition: "industrial shell",
      vacancy_duration: "10 months",
      description: "Industrial space with floor drains, 3-phase power, and drive-in access. Previously used as an auto shop. Ideal conversion opportunity for a brewery, distillery, or production kitchen. Foster Road is an emerging corridor.",
      amenities: ["Floor drains", "3-phase power", "Drive-in access", "High ceilings", "Off-street parking"],
      floor: "Ground",
      contact_email: "leasing@portlandcommons.org",
      lat: 45.4835,
      lon: -122.6108,
    },
    {
      title: "Boutique on Belmont",
      address: "3438 SE Belmont St, Portland, OR 97214",
      neighborhood: "Belmont",
      sqft: 1100,
      space_type: "retail",
      asking_rent: 25.0,
      pcb_terms: { popup_available: true, popup_minimum: "1 month", popup_rate: 1400, graduated_rent: true, graduated_schedule: "Year 1: 55%, Year 2: 80%, Year 3: 100%" },
      condition: "move-in ready",
      vacancy_duration: "3 months",
      description: "Charming retail space on SE Belmont with original hardwood floors and tin ceiling. Strong neighborhood identity and loyal local shoppers. Previous tenant was a vintage home goods store.",
      amenities: ["Hardwood floors", "Tin ceiling", "Display windows", "Street parking", "Bike lane"],
      floor: "Ground",
      contact_email: "leasing@portlandcommons.org",
      lat: 45.5160,
      lon: -122.6312,
    },
    {
      title: "Tech Office in Slabtown",
      address: "2155 NW Raleigh St, Portland, OR 97210",
      neighborhood: "Slabtown",
      sqft: 6000,
      space_type: "office",
      asking_rent: 32.0,
      pcb_terms: { popup_available: false, graduated_rent: true, graduated_schedule: "Year 1: 70%, Year 2: 85%, Year 3: 100%" },
      condition: "move-in ready",
      vacancy_duration: "9 months",
      description: "Modern Class A office space in the Slabtown tech corridor. Open floor plan with server room, shower facilities, and secure bike storage. Near the streetcar and surrounded by restaurants and amenities.",
      amenities: ["Server room", "Showers", "Bike storage", "Streetcar adjacent", "On-site parking"],
      floor: "3rd",
      contact_email: "leasing@portlandcommons.org",
      lat: 45.5345,
      lon: -122.6956,
    },
    {
      title: "Community Space in St. Johns",
      address: "8234 N Lombard St, Portland, OR 97203",
      neighborhood: "St. Johns",
      sqft: 2200,
      space_type: "flex",
      asking_rent: 14.0,
      pcb_terms: { popup_available: true, popup_minimum: "2 weeks", popup_rate: 600, graduated_rent: true, graduated_schedule: "Year 1: 40%, Year 2: 60%, Year 3: 80%, Year 4: 100%" },
      condition: "needs renovation",
      vacancy_duration: "18 months",
      description: "Flexible space in the St. Johns town center with strong community anchor potential. Previous use as a community meeting hall. Deep graduated rent discount reflects the neighborhood's desire for activation. PCB priority zone.",
      amenities: ["Cathedral District", "Bus line", "Off-street parking", "Community anchor"],
      floor: "Ground",
      contact_email: "leasing@portlandcommons.org",
      lat: 45.5905,
      lon: -122.7514,
    },
    {
      title: "Drive-Through Retail on MLK",
      address: "4511 NE Martin Luther King Jr Blvd, Portland, OR 97211",
      neighborhood: "King",
      sqft: 1800,
      space_type: "retail",
      asking_rent: 20.0,
      pcb_terms: { popup_available: true, graduated_rent: true, graduated_schedule: "Year 1: 50%, Year 2: 75%, Year 3: 100%" },
      condition: "white box",
      vacancy_duration: "6 months",
      description: "Freestanding retail building with drive-through window on MLK Blvd. Excellent vehicle visibility and access. Suitable for coffee shop, fast-casual restaurant, or service retail. PCB priority corridor.",
      amenities: ["Drive-through", "Freestanding", "Parking lot", "High visibility", "Bus stop"],
      floor: "Ground",
      contact_email: "leasing@portlandcommons.org",
      lat: 45.5560,
      lon: -122.6616,
    },
    {
      title: "Medical/Wellness Suite near OHSU",
      address: "3303 SW Bond Ave, Portland, OR 97239",
      neighborhood: "South Waterfront",
      sqft: 2600,
      space_type: "office",
      asking_rent: 35.0,
      pcb_terms: { popup_available: false, graduated_rent: true, graduated_schedule: "Year 1: 70%, Year 2: 85%, Year 3: 100%" },
      condition: "move-in ready",
      vacancy_duration: "4 months",
      description: "Professional suite in the South Waterfront district, ideal for medical, dental, wellness, or professional services. Near OHSU and the aerial tram. Modern building with abundant natural light and river views.",
      amenities: ["River views", "Near OHSU", "Aerial tram", "Structured parking", "Fiber internet"],
      floor: "4th",
      contact_email: "leasing@portlandcommons.org",
      lat: 45.4979,
      lon: -122.6712,
    },
  ];

  for (const l of listings) {
    await sql`
      INSERT INTO real_estate.listings (
        title, address, neighborhood, sqft, space_type, asking_rent,
        pcb_terms, condition, vacancy_duration, description, amenities,
        floor, contact_email, lat, lon, listed_date, status
      ) VALUES (
        ${l.title}, ${l.address}, ${l.neighborhood}, ${l.sqft}, ${l.space_type},
        ${l.asking_rent}, ${JSON.stringify(l.pcb_terms)}::jsonb, ${l.condition},
        ${l.vacancy_duration}, ${l.description}, ${l.amenities},
        ${l.floor}, ${l.contact_email}, ${l.lat}, ${l.lon},
        CURRENT_DATE - (random() * 60)::int, 'available'
      )
    `;
  }

  console.log(`Seeded ${listings.length} listings into real_estate.listings`);
  await sql.end();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
